name: Build Marlin Firmware

on:
  #push:
  #  branches:
  #    - master
  #  paths:
  #    - 'Firmware/Configuration/**.h'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_push:
    name: Compile and Push Firmware
    runs-on: ubuntu-latest
    env:
      BOARD: STM32F070RB_malyan

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Compile firmware
        run: |
          docker run \
            -u root:root \
            -e BOARD \
            -e UPDATE_FORCE=true \
            -e USE_TAG=2.0.6.1 \
            -v $(pwd)/Firmware/Builds:/home/platformio/build \
            -v $(pwd)/Firmware/Configuration:/home/platformio/CustomConfiguration \
            frealmyr/marlin-build:latest

      #- name: Push firmware
      #  run: |
      #    git config user.name github-actions
      #    git config user.email github-actions@github.com
      #    git add .
      #    git commit -m "Compiled firmware"
      #    git push
      
    
    # just for debugging purposes - print the file-structure
      - name: Print Folder Structure
        run: |
          sudo apt-get install tree
          tree -a
    # copy firmware to atrifacts
      - name: Save firmware.bin
        uses: actions/upload-artifact@v2
        with:
          name: update.bin
          path: ${{ github.workspace }}/.pio/build/STM32F070RB_malyan/firmware.bin
      - name: Save fcupdate.flg
        uses: actions/upload-artifact@v2
        with:
          name: fcupdate.flg
          path: ${{ github.workspace }}/.pio/build/STM32F070RB_malyan/firmware.bin
